language: java
sudo: true
dist: trusty

stages:
  - checkstyle
  - test
  - Integration Test
  - coveralls

jdk:
  - oraclejdk11
  - openjdk10
  - oraclejdk9
  - oraclejdk8

matrix:
  include:
  - stage: Integration Test
    jdk: oraclejdk8
    env: CUSTOM_MVN_VERION="3.0"
  - jdk: oraclejdk8
    env: CUSTOM_MVN_VERION="3.0.5"
  - jdk: oraclejdk8
    env: CUSTOM_MVN_VERION="3.1.1"
  - jdk: oraclejdk8
    env: CUSTOM_MVN_VERION="3.2.5"
  - jdk: oraclejdk8
    env: CUSTOM_MVN_VERION="3.3.9"
  - jdk: oraclejdk9
    env: CUSTOM_MVN_VERION="3.5.0"
  - jdk: oraclejdk9
    env: CUSTOM_MVN_VERION="3.5.4"
  - jdk: oraclejdk9
    env: CUSTOM_MVN_VERION="3.6.0"
  - stage: checkstyle
    jdk: oraclejdk9
    script: mvn clean verify -Pcheckstyle -Dcheckstyle.version=8.2 -Dmaven.test.skip=true -B
    env: CHECKSTYLE=8.2
  - stage: checkstyle
    jdk: oraclejdk8
    script: mvn clean verify -Pcheckstyle -Dmaven.test.skip=true -B
    env: CHECKSTYLE=8.2
  - stage: coveralls
    jdk: oraclejdk8
    secure: "nWocmaofFk759rTMC37hJ5qbLN9V7B5jwxuR15OhsHcE4WuijsatbEP6YY4Z6zomozKEaPYVA8rLbbpSY2B6JQffe4NV975647CZisp/WtJmkvsLEbio0mkJ2Jw11aHZ+o3OI17Kh/vxzVrjYusFuMok/AADT7bV9cBk/2l5u9I="
    script: mvn clean test jacoco:report coveralls:report -Pcoveralls -DrepoToken=${COVERALLS_REPO_TOKEN} -B

install:
  - if [[ -n "${CUSTOM_MVN_VERION}" ]]; then
      echo "Download Maven ${CUSTOM_MVN_VERION}....";
      if [[ "${CUSTOM_MVN_VERION}" == "3.0" ]]; then
        wget https://archive.apache.org/dist/maven/binaries/apache-maven-3.0-bin.zip || travis_terminate 1;
      else
        wget https://archive.apache.org/dist/maven/maven-3/${CUSTOM_MVN_VERION}/binaries/apache-maven-${CUSTOM_MVN_VERION}-bin.zip || travis_terminate 1;
      fi;
      unzip -qq apache-maven-${CUSTOM_MVN_VERION}-bin.zip || travis_terminate 1;
      export M2_HOME=$PWD/apache-maven-${CUSTOM_MVN_VERION};
      export PATH=$M2_HOME/bin:$PATH;
      mvn -version;
    fi

script:
  - mvn clean test install -B
  - mvn clean initialize -Pdemo -Dmaven.test.skip=true -B
  - /bin/bash -c '[[ -f target/testing.properties ]] && cat target/testing.properties || travis_terminate 1;'
