language: java
sudo: true
dist: trusty

stages:
  - checkstyle
  - test
  - Integration Test
  - coveralls
  - deploy

jdk:
  - oraclejdk11
  - openjdk10
  - oraclejdk9
  - oraclejdk8

matrix:
  include:
  - stage: Integration Test
    jdk: oraclejdk8
    env: CUSTOM_MVN_VERION="3.0"
  - jdk: oraclejdk8
    env: CUSTOM_MVN_VERION="3.0.5"
  - jdk: oraclejdk8
    env: CUSTOM_MVN_VERION="3.1.1"
  - jdk: oraclejdk8
    env: CUSTOM_MVN_VERION="3.2.5"
  - jdk: oraclejdk8
    env: CUSTOM_MVN_VERION="3.3.9"
  - jdk: oraclejdk9
    env: CUSTOM_MVN_VERION="3.5.0"
  - jdk: oraclejdk9
    env: CUSTOM_MVN_VERION="3.5.4"
  - jdk: oraclejdk9
    env: CUSTOM_MVN_VERION="3.6.0"
  - stage: checkstyle
    jdk: oraclejdk9
    script: mvn clean verify -Pcheckstyle -Dcheckstyle.version=8.2 -Dmaven.test.skip=true -B
    env: CHECKSTYLE=8.2
  - stage: checkstyle
    jdk: oraclejdk8
    script: mvn clean verify -Pcheckstyle -Dmaven.test.skip=true -B
    env: CHECKSTYLE=8.2
  - stage: coveralls
    jdk: oraclejdk8
    env:
      secure: "nWocmaofFk759rTMC37hJ5qbLN9V7B5jwxuR15OhsHcE4WuijsatbEP6YY4Z6zomozKEaPYVA8rLbbpSY2B6JQffe4NV975647CZisp/WtJmkvsLEbio0mkJ2Jw11aHZ+o3OI17Kh/vxzVrjYusFuMok/AADT7bV9cBk/2l5u9I="
    script: mvn clean test jacoco:report coveralls:report -Pcoveralls -DrepoToken=${COVERALLS_REPO_TOKEN} -B
  - stage: deploy
    jdk: oraclejdk8
    script:
        - if [ "$TRAVIS_PULL_REQUEST" != "false" ] || [ "$TRAVIS_BRANCH" != "master" ]; then echo "the deploy job only runs for the master branch. This build will now exit"; exit 0; fi
        - if [ "$TRAVIS_PULL_REQUEST" == "false" ] && [ "$TRAVIS_BRANCH" == "master" ]; then mvn clean deploy --settings=".buildscript/settings.xml"; fi
    env:
      - secure: "o1dqRCwF2bD7Ccb276lQRwq4TVyX74WHz3Gv5kF4yB3BNkrYScoZaCrB0upn6TbJsC9krjao7pOLhYG6tLqQbmy8FTii/gxTTNRf+Ln4TkNqAOZ9dddj6cSOTzcRq2baZoTgZtNYNBhYtU5lPPihYp9l9jN99g76LRDzrBGncAw="
      - secure: "Gm6/TwMCtiw+UEUNuK6c1wrTron3IRvOLdqyOdjCsM/ohYN/xYw3GJXKPVsjMaxNzN+x9/tyMRRHTt9AiOAtp7pktritpKK2LwvCFij6pqpiTitBSz6+h9XsWI4iP0L7rwtS5K5Yc/JiK7iN2660dSmzLfDviD12EneAhPMV01Y="

install:
  - if [[ -n "${CUSTOM_MVN_VERION}" ]]; then
      echo "Download Maven ${CUSTOM_MVN_VERION}....";
      if [[ "${CUSTOM_MVN_VERION}" == "3.0" ]]; then
        wget https://archive.apache.org/dist/maven/binaries/apache-maven-3.0-bin.zip || travis_terminate 1;
      else
        wget https://archive.apache.org/dist/maven/maven-3/${CUSTOM_MVN_VERION}/binaries/apache-maven-${CUSTOM_MVN_VERION}-bin.zip || travis_terminate 1;
      fi;
      unzip -qq apache-maven-${CUSTOM_MVN_VERION}-bin.zip || travis_terminate 1;
      export M2_HOME=$PWD/apache-maven-${CUSTOM_MVN_VERION};
      export PATH=$M2_HOME/bin:$PATH;
      mvn -version;
    fi

script:
  - mvn clean test install -B
  - mvn clean initialize -Pdemo -Dmaven.test.skip=true -B
  - /bin/bash -c '[[ -f target/testing.properties ]] && cat target/testing.properties || travis_terminate 1;'
